# Numpy



In [2]:
import numpy as np



In [3]:
x = [1, 13, 343, 2355, 5]

In [4]:
np_x = np.array(x)

In [5]:
print(type(np_x))

<type 'numpy.ndarray'>


In [6]:
#Let's say we want to double X
double_x = np_x * 2

In [7]:
print(double_x)

[   2   26  686 4710   10]


In [8]:
#get all numbers higher than 100
hundred = double_x > 100
double_x[hundred]

array([ 686, 4710])

In [9]:
#get numbers less than 10
ten = double_x < 10
double_x[ten]

array([2])

In [10]:
#some things are different in numpy vs arrays and others are the same for example
x[2]

343

In [11]:
x[1:3]

[13, 343]

In [12]:
weight = [124, 99, 56, 140]
height = [72, 55, 43, 78]

np_weight = np.array(weight)
np_height = np.array(height)

# numpy 2d arrays



In [13]:
hw = np.array([height, weight])

In [14]:
hw

array([[ 72,  55,  43,  78],
       [124,  99,  56, 140]])

In [15]:
hw.shape
#2 rows, 4 columns

(2, 4)

In [16]:
#select row then column
hw[0][1]



55

In [17]:
#or
hw[0,1]

55

In [18]:
#all rows, and columns 1 and 2
hw[:, 1:3]

array([[55, 43],
       [99, 56]])

In [19]:
#numpy is great at vector arithmatic
hw_1 = hw * 3

In [20]:
hw_1

array([[216, 165, 129, 234],
       [372, 297, 168, 420]])

In [21]:
convert = [3, 2, .5, 3]
divide_hw_1 = hw_1 / convert

In [22]:
divide_hw_1

array([[  72. ,   82.5,  258. ,   78. ],
       [ 124. ,  148.5,  336. ,  140. ]])

In [23]:
#numpy statistics


In [24]:
avg_h = np.mean(hw[:, 0])

In [25]:
avg_h

98.0

In [26]:
median_h = np.median(hw[:, 0])

In [27]:
median_h

98.0

In [28]:
hw

array([[ 72,  55,  43,  78],
       [124,  99,  56, 140]])

In [29]:
hw[:, 0]

array([ 72, 124])

In [30]:
sort = np.sort(hw[:, 0])

In [31]:
#make randomness
#distriburtion mean = 1.75, distribution standard deviation= 0.20, numpber of samples = 5000
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [32]:
height

array([ 1.95,  1.94,  1.87, ...,  1.69,  1.86,  1.85])

In [33]:
weight

array([ 56.14,  72.41,  73.38, ...,  62.51,  48.7 ,  52.39])

In [34]:
mean_height = np.mean(height)

In [35]:
mean_height

1.7523919999999997

In [36]:
median_height = np.median(height)

In [37]:
median_height

1.75

In [38]:
np_pretend_city = np.column_stack((height, weight))

In [39]:
np_pretend_city

array([[  1.95,  56.14],
       [  1.94,  72.41],
       [  1.87,  73.38],
       ..., 
       [  1.69,  62.51],
       [  1.86,  48.7 ],
       [  1.85,  52.39]])

In [40]:
average = np.mean(np_pretend_city)

In [41]:
average

31.055713000000001

In [43]:
median = np.median(np_pretend_city[:,0])

median

In [44]:
median

1.75

In [45]:
standard_deviation = np.std(np_pretend_city[:,0])

In [46]:
standard_deviation

0.19875009015343867

In [47]:
#correlation betweenheight and weight

correlation = np.corrcoef(np_pretend_city[:,0], np_pretend_city[:, 1])

In [48]:
correlation

array([[ 1.       ,  0.0265336],
       [ 0.0265336,  1.       ]])

# thoughts

You have a series of fruits 'apple', 'orange', 'blueberry' and weights. you believe oranges are the heaviest fruit but no one believes you. 



In [53]:
fruits = ['orange', 'apple', 'apple', 'apple', 'blueberry', 'blueberry', 'orange', 'orange', 'orange']

In [54]:
weights = [212, 170, 180, 177, 190, 10, 9, 223, 240]

In [55]:
np_fruits = np.array(fruits)
np_weights = np.array(weights)

In [56]:
orange_weights = np_weights[np_fruits == 'orange']

In [57]:
other_fruit_weights = np_weights[np_fruits != 'orange']

In [58]:
orange_weight_median = np.median(orange_weights)

In [59]:
other_fruit_weights_median = np.median(other_fruit_weights)

In [61]:
print(orange_weight_median)
print(other_fruit_weights_median)

217.5
177.0
