# Numpy



In [1]:
import numpy as np



In [2]:
x = [1, 13, 343, 2355, 5]

In [3]:
np_x = np.array(x)

In [4]:
print(type(np_x))

<type 'numpy.ndarray'>


In [5]:
#Let's say we want to double X
double_x = np_x * 2

In [6]:
print(double_x)

[   2   26  686 4710   10]


In [7]:
#get all numbers higher than 100
hundred = double_x > 100
double_x[hundred]

array([ 686, 4710])

In [8]:
#get numbers less than 10
ten = double_x < 10
double_x[ten]

array([2])

In [9]:
#some things are different in numpy vs arrays and others are the same for example
x[2]

343

In [10]:
x[1:3]

[13, 343]

In [11]:
weight = [124, 99, 56, 140]
height = [72, 55, 43, 78]

np_weight = np.array(weight)
np_height = np.array(height)

# numpy 2d arrays



In [14]:
hw = np.array([height, weight])

In [15]:
hw

array([[ 72,  55,  43,  78],
       [124,  99,  56, 140]])

In [17]:
hw.shape
#2 rows, 4 columns

(2, 4)

In [18]:
#select row then column
hw[0][1]



55

In [19]:
#or
hw[0,1]

55

In [21]:
#all rows, and columns 1 and 2
hw[:, 1:3]

array([[55, 43],
       [99, 56]])

In [23]:
#numpy is great at vector arithmatic
hw_1 = hw * 3

In [24]:
hw_1

array([[216, 165, 129, 234],
       [372, 297, 168, 420]])

In [26]:
convert = [3, 2, .5, 3]
divide_hw_1 = hw_1 / convert

In [27]:
divide_hw_1

array([[  72. ,   82.5,  258. ,   78. ],
       [ 124. ,  148.5,  336. ,  140. ]])

In [28]:
#numpy statistics


In [29]:
avg_h = np.mean(hw[:, 0])

In [30]:
avg_h

98.0

In [31]:
median_h = np.median(hw[:, 0])

In [32]:
median_h

98.0

In [33]:
hw

array([[ 72,  55,  43,  78],
       [124,  99,  56, 140]])

In [34]:
hw[:, 0]

array([ 72, 124])

In [35]:
sort = np.sort(hw[:, 0])

In [44]:
#make randomness
#distriburtion mean = 1.75, distribution standard deviation= 0.20, numpber of samples = 5000
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [45]:
height

array([ 1.62,  2.15,  1.86, ...,  1.42,  1.61,  1.69])

In [46]:
weight

array([ 62.17,  58.7 ,  23.26, ...,  48.42,  63.71,  50.39])

In [47]:
mean_height = np.mean(height)

In [48]:
mean_height

1.7539880000000001

In [49]:
median_height = np.median(height)

In [50]:
median_height

1.75

In [51]:
np_pretend_city = np.column_stack((height, weight))

In [52]:
np_pretend_city

array([[  1.62,  62.17],
       [  2.15,  58.7 ],
       [  1.86,  23.26],
       ..., 
       [  1.42,  48.42],
       [  1.61,  63.71],
       [  1.69,  50.39]])